before_install:
  - curl https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-5.3.1.deb -o elasticsearch.deb
  - sudo dpkg -i --force-confnew elasticsearch.deb
  - sudo chown -R elasticsearch:elasticsearch /etc/default/elasticsearch
  - sudo service elasticsearch restart
language: go
os: linux
dist: xenial
go: 1.x
script: go test -v